default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["database"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: <%= ENV["database"] %>

production:
  <<: *default
  database: <%= ENV["database"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>

